# Install taskfile with
# sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/go/bin

version: "3"

silent: true

tasks:
  default:
    cmds:
      - task: test

  clean:
    desc: Clean up working directory
    cmds:
      - rm -rf k6 .task node_modules

  test:
    cmds:
      - k6 run tests/findBetween.js
      - k6 run tests/splitString.js
      - k6 run tests/splitInt.js
      - k6 run -e VAR_STRING=string tests/getString.js
      - k6 run -e VAR_NUM=33 -e NOT_NUM=a tests/getInt.js
      - k6 run -e VAR_NUM=33 -e VAR_NUM2_1='44:561' -e VAR_NUM2_2='561:14' tests/getInt2.js
